import assert from 'node:assert/strict';
import {createHandler} from './netlify/functions/site.mjs';
const map=new Map();const store={list:async()=>({blobs:[...map.keys()].map(key=>({key}))}),get:async key=>map.get(key)||null,setJSON:async(key,v)=>{if(map.has(key))return {modified:false};map.set(key,structuredClone(v));return {modified:true};}};
let handler=createHandler(()=>store);let cookie='';
const call=(path,body,auth=true)=>handler(new Request('https://example.netlify.app'+path,{method:body?'POST':'GET',headers:{...(auth?{cookie}:{}),...(body?{'origin':'https://example.netlify.app','content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}));
assert.equal((await call('/expenses.json',null,false)).status,401);
assert.equal((await call('/api/database',null,false)).status,401);
const login=await handler(new Request('https://example.netlify.app/login',{method:'POST',headers:{origin:'https://example.netlify.app'},body:new URLSearchParams({password:'aldo4'})}));assert.equal(login.status,303);cookie=login.headers.get('set-cookie').split(';')[0];
assert.equal((await call('/')).status,200);
const initial=await (await call('/expenses.json')).json();const sum=d=>d.records.reduce((a,r)=>a+(r.amountCents||0),0);
const attachment={mime:'application/pdf',data:Buffer.from('%PDF-1.4\nTest').toString('base64')};
const inv={type:'invoice',date:'2026-10-07',supplier:'Fornitore test',number:'TEST-1',group:'Cucina',total:1234,attachment};
assert.equal((await call('/api/records',inv)).status,201);assert.equal((await call('/api/records',inv)).status,409);
handler=createHandler(()=>store);assert.equal(sum(await (await call('/expenses.json')).json()),sum(initial)+1234);
const c={type:'closing',date:'2026-10-07',bar:5000,kitchen:4000,pos:6000,cash:3000,total:9000,takeaway:0,attachment};assert.equal((await call('/api/records',c)).status,201);assert.equal((await call('/api/records',c)).status,409);
assert.equal((await call('/api/records',{...c,date:'2026-10-05'})).status,409);
const closings=await (await call('/closings.json')).json();assert.equal(closings.at(-1).reportedTotal,9000);
const url=closings.at(-1).sources[0];assert.equal((await call(url,null,false)).status,401);assert.equal((await call(url)).status,200);
const db=await (await call('/api/database')).json();assert.equal(db.uploads.length,2);assert.equal(db.uploads[0].attachment.data,attachment.data);
assert.equal((await call('/server-config.json')).status,404);
assert.equal((await call('/api/records',{...inv,number:'X',attachment:{mime:'text/html',data:'AA=='}})).status,400);
console.log('PASS: login, protected data/assets, invoice/closing writes, duplicate checks, persisted reads, totals, JSON backup, upload validation.');
