import assert from 'node:assert/strict';
import {createHandler} from './netlify/functions/site.mjs';
const map=new Map();let serial=0;const store={list:async({prefix})=>({blobs:[...map.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}),get:async key=>map.get(key)?.data||null,getWithMetadata:async key=>map.has(key)?structuredClone(map.get(key)):null,setJSON:async(key,v,options={})=>{const prev=map.get(key);if(options.onlyIfNew&&prev||options.onlyIfMatch&&options.onlyIfMatch!==prev?.etag)return {modified:false};const etag=String(++serial);map.set(key,{data:structuredClone(v),etag});return {modified:true,etag};}};
let handler=createHandler(()=>store);let cookie='';
const call=(path,body,auth=true)=>handler(new Request('https://example.netlify.app'+path,{method:body?'POST':'GET',headers:{...(auth?{cookie}:{}),...(body?{'origin':'https://example.netlify.app','content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}));
assert.equal((await call('/expenses.json',null,false)).status,401);
assert.equal((await call('/api/database',null,false)).status,401);
const login=await handler(new Request('https://example.netlify.app/login',{method:'POST',headers:{origin:'https://example.netlify.app'},body:new URLSearchParams({password:process.env.TEST_PASSWORD||''})}));assert.equal(login.status,303);cookie=login.headers.get('set-cookie').split(';')[0];
assert.equal((await call('/')).status,200);
const initial=await (await call('/expenses.json')).json();const sum=d=>d.records.reduce((a,r)=>a+(r.amountCents||0),0);
const attachment={mime:'application/pdf',data:Buffer.from('%PDF-1.4\nTest').toString('base64')};
const inv={type:'invoice',date:'2026-10-07',supplier:'Fornitore test',number:'TEST-1',group:'Cucina',total:1234,attachment};
assert.equal((await call('/api/records',inv)).status,201);assert.equal((await call('/api/records',inv)).status,409);
handler=createHandler(()=>store);assert.equal(sum(await (await call('/expenses.json')).json()),sum(initial)+1234);
const c={type:'closing',date:'2026-10-07',bar:5000,kitchen:4000,pos:6000,cash:3000,total:9000,takeaway:0,attachment};assert.equal((await call('/api/records',c)).status,201);assert.equal((await call('/api/records',c)).status,409);
assert.equal((await call('/api/records',{...c,date:'2026-10-05'})).status,409);
const closings=await (await call('/closings.json')).json();assert.equal(closings.at(-1).reportedTotal,9000);
const url=closings.at(-1).sources[0];assert.equal((await call(url,null,false)).status,401);assert.equal((await call(url)).status,200);
const db=await (await call('/api/database')).json();assert.equal(db.uploads.length,2);assert.equal(db.uploads[0].attachment.data,attachment.data);
assert.equal((await call('/server-config.json')).status,404);
assert.equal((await call('/api/records',{...inv,number:'X',attachment:{mime:'text/html',data:'AA=='}})).status,400);
console.log('PASS: login, protected data/assets, invoice/closing writes, duplicate checks, persisted reads, totals, JSON backup, upload validation.');

const managed=async()=>await (await call('/api/manage')).json();
let seeded=(await managed()).find(x=>x.id==='exp-069');
const editInvoice={action:'edit',id:seeded.id,revision:seeded.revision,date:'2026-10-05',supplier:seeded.record.supplier,number:'26961',group:'Bar',amountCents:80000};
assert.equal((await call('/api/manage',editInvoice,null)).status,401);
assert.equal((await call('/api/manage',editInvoice)).status,200);
assert.equal((await call('/api/manage',editInvoice)).status,409);
assert.equal((await (await call('/invoices.json')).json())[0].total,800);
seeded=(await managed()).find(x=>x.id==='exp-069');
assert.equal((await call('/api/manage',{id:seeded.id,revision:seeded.revision,action:'delete'})).status,200);
assert.equal((await (await call('/invoices.json')).json()).length,0);
assert.equal((await (await call('/expenses.json')).json()).records.some(r=>r.id==='exp-069'),false);
let closing=(await managed()).find(x=>x.id==='closing-2026-10-05');
let editClosing={action:'edit',id:closing.id,revision:closing.revision,date:'2026-10-05',barTotal:10000,kitchenTotal:20000,pos:15000,cashAfterOutflow:15000,takeawayHandwritten:0,reportedTotal:30000};
assert.equal((await call('/api/manage',{...editClosing,date:'2026-10-04'})).status,409);
assert.equal((await call('/api/manage',{...editClosing,pos:-1})).status,400);
assert.equal((await call('/api/manage',editClosing)).status,200);
assert.equal((await (await call('/closings.json')).json()).find(r=>r.id===closing.id).reportedTotal,30000);
closing=(await managed()).find(x=>x.id===closing.id);
assert.equal((await call('/api/manage',{action:'delete',id:closing.id,revision:closing.revision})).status,200);
handler=createHandler(()=>store);
assert.equal((await (await call('/closings.json')).json()).some(r=>r.id===closing.id),false);
for(const item of (await managed()).filter(x=>!x.seed)){
 assert.equal((await call('/api/manage',{action:'delete',id:item.id,revision:item.revision})).status,200);
}
assert.equal((await (await call('/api/records')).json()).length,0);
const backup=await (await call('/api/database')).json();assert.equal(backup.changes['exp-069'].deleted,true);assert.equal(backup.uploads.length,2);
console.log('PASS: edits/deletions for original and uploaded records, invoice synchronization, total recomputation, stale revisions, duplicate dates, invalid edits, retained originals and restart persistence.');

const categories=['Stipendi dipendenti','Commercialista','Acqua','Corrente','Guasti e manutenzione','Innovazioni e miglioramenti','Amazon','Cinese','Supermercato'];
const baseExpenses=await (await call('/expenses.json')).json();
const monthSum=(d,m)=>d.records.filter(r=>r.date.startsWith(m)).reduce((s,r)=>s+(r.amountCents||0),0);
let managementIds=[];
for(const [i,category] of categories.entries()){
 const expense={type:'expense',category,supplier:'Prova '+category,date:i===0?'2026-09-30':'2026-10-07',total:10000+i,group:'Varie',note:'Periodo di riferimento',requestId:`00000000-0000-4000-8000-${String(i).padStart(12,'0')}`,...(i===8?{attachment}:{})};
 const r=await call('/api/records',expense);assert.equal(r.status,201);managementIds.push((await r.json()).id);
 assert.equal((await call('/api/records',expense)).status,409);
}
handler=createHandler(()=>store);
let expenses=await (await call('/expenses.json')).json();assert.equal(monthSum(expenses,'2026-09'),monthSum(baseExpenses,'2026-09')+10000);assert.equal(monthSum(expenses,'2026-10'),monthSum(baseExpenses,'2026-10')+80036);
assert.equal((await call('/api/attachment/'+managementIds[0])).status,404);
assert.equal((await call('/api/attachment/'+managementIds[8])).status,200);
let item=(await managed()).find(x=>x.id===managementIds[0]);
const edit={action:'edit',id:item.id,revision:item.revision,date:'2026-10-08',amountCents:20000,supplier:'Stipendi aggiornati',number:'',group:'Cucina',category:categories[0],note:'Ottobre'};
assert.equal((await call('/api/manage',edit)).status,200);
expenses=await (await call('/expenses.json')).json();assert.equal(monthSum(expenses,'2026-09'),monthSum(baseExpenses,'2026-09'));assert.equal(monthSum(expenses,'2026-10'),monthSum(baseExpenses,'2026-10')+100036);
item=(await managed()).find(x=>x.id===managementIds[0]);assert.equal((await call('/api/manage',{...edit,revision:item.revision,category:'Inventata'})).status,400);
assert.equal((await call('/api/manage',{action:'delete',id:item.id,revision:item.revision})).status,200);
expenses=await (await call('/expenses.json')).json();assert.equal(monthSum(expenses,'2026-10'),monthSum(baseExpenses,'2026-10')+80036);
for(const bad of [{category:'Inventata'},{total:-1},{total:1.5},{total:0},{date:'2026-02-30'}])assert.equal((await call('/api/records',{type:'expense',category:categories[0],date:'2026-10-07',supplier:'Test',total:100,group:'Varie',note:'',requestId:'00000000-0000-4000-8000-000000000099',...bad})).status,400);
assert.equal((await call('/spese-gestione.html',null,false)).status,401);
assert.equal((await call('/spese-gestione.html')).status,200);
const expenseBackup=await (await call('/api/database')).json();assert.equal(expenseBackup.uploads.filter(r=>r.type==='expense').length,9);
console.log('PASS: all nine management categories, optional attachments, idempotency, month allocation, edit/move/delete totals, validation, persistence and backup.');
