(function(){
const groups=['Bar','Cucina','Varie','Da chiarire'];
function monthKey(date=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit'}).formatToParts(date);return parts.find(p=>p.type==='year').value+'-'+parts.find(p=>p.type==='month').value;}
function summarize(rows){return {total:rows.reduce((n,r)=>n+(Number.isInteger(r.amountCents)?r.amountCents:0),0),pending:rows.filter(r=>r.amountCents===null).length,groups:Object.fromEntries(groups.map(g=>[g,rows.filter(r=>r.group===g).reduce((n,r)=>n+(r.amountCents??0),0)]))};}
if(typeof module!=='undefined'&&module.exports){module.exports={monthKey,summarize};return;}
const fmt=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}),money=c=>fmt.format(c/100);
const monthName=m=>new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T12:00:00Z'));
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function renderView(target,month,data){const isHistory=target==='history-view';const root=document.getElementById(target);root.replaceChildren();const all=data.records.filter(r=>r.date.startsWith(month)).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));const sums=summarize(all);
if(!all.length){const box=el('div',undefined,'panel');box.append(el('h2','Spese da acquisire'),el('p','Nessuna annotazione disponibile per '+monthName(month)+'. Questo non significa che le spese siano zero.'));root.append(box);return;}
const summary=el('div',undefined,'notice');summary.append(el('strong','Totale importi leggibili: '+money(sums.total)),el('p',all.length+' annotazioni · '+sums.pending+' importi da confermare, esclusi dal totale. Il totale include anche movimenti ancora da classificare.'),el('p',data.coverage[month]||'Completezza del mese da verificare.'));root.append(summary);
const cards=el('div',undefined,'cards');cards.style.gridTemplateColumns='repeat(auto-fit,minmax(180px,1fr))';groups.forEach(g=>{const rows=all.filter(r=>r.group===g),info=summarize(rows),box=el('article',undefined,'card');box.append(el('div',g,'eyebrow'),el('strong',money(info.total)),el('small',rows.length+' voci'+(info.pending?' · '+info.pending+' importi in sospeso':'')));cards.append(box)});root.append(cards);
const controls=el('div',undefined,'tools'),search=el('input');search.type='search';search.placeholder='Cerca fornitore, categoria o nota…';search.setAttribute('aria-label','Cerca nelle spese di '+monthName(month));const select=el('select');select.setAttribute('aria-label','Filtra per reparto');['Tutti i reparti',...groups].forEach((g,i)=>{const option=el('option',g);option.value=i?g:'';select.append(option)});controls.append(search,select);root.append(controls);
const count=el('p');count.setAttribute('aria-live','polite');root.append(count);const box=el('div',undefined,'tablebox'),table=el('table'),head=el('thead'),tr=el('tr');(isHistory?['Data','Reparto / categoria','Importo']:['Data','Voce e note','Reparto / categoria','Importo']).forEach(t=>tr.append(el('th',t)));head.append(tr);const body=el('tbody');table.append(head,body);box.append(table);root.append(box);
function draw(){body.replaceChildren();const query=search.value.trim().toLocaleLowerCase('it');const rows=all.filter(r=>(!select.value||r.group===select.value)&&[r.name,r.category,r.note].join(' ').toLocaleLowerCase('it').includes(query));const sum=summarize(rows);count.textContent=rows.length+' voci visualizzate · subtotale leggibile '+money(sum.total)+(sum.pending?' · '+sum.pending+' importi esclusi da confermare':'');rows.forEach(r=>{const tr=el('tr');const date=el('td',r.date.slice(8)+'/'+r.date.slice(5,7));const name=el('td',r.name);if(r.note)name.append(el('small',r.note));const link=el('a','Foto del registro ↗');link.href=r.source;link.target='_blank';link.rel='noopener';link.style.fontSize='12px';name.append(el('br'),link);const group=el('td',r.group);group.append(el('small',r.category));const amount=el('td',r.amountCents===null?'Da confermare':money(r.amountCents),'price');if(r.amountCents===null&&r.candidateCents!==null)amount.append(el('small','Lettura possibile: '+money(r.candidateCents)));if(isHistory)tr.append(date,group,amount);else tr.append(date,name,group,amount);body.append(tr)});if(!rows.length){const tr=el('tr'),td=el('td','Nessuna voce corrisponde alla ricerca.');td.colSpan=isHistory?3:4;tr.append(td);body.append(tr)}}search.oninput=draw;select.onchange=draw;draw();
const notes=el('details',undefined,'panel');notes.style.marginTop='22px';notes.append(el('summary','Fonti e criteri di lettura'));data.notes.forEach(n=>notes.append(el('p',n)));root.append(notes);
}
fetch('expenses.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{function refresh(){const current=monthKey(),rows=data.records.filter(r=>r.date.startsWith(current)),summary=summarize(rows);document.getElementById('expense-title').textContent='Spese · '+monthName(current);document.getElementById('current-expense-label').textContent='Spese e uscite · '+monthName(current);document.getElementById('current-expense-total').textContent=rows.length?money(summary.total):'Da acquisire';document.getElementById('current-expense-note').textContent=rows.length?'Totale leggibile · '+summary.pending+' importi esclusi da confermare. Raccolta parziale.':'Nessuna spesa ancora acquisita per il mese corrente.';renderView('expense-view',current,data);const months=[...new Set(data.records.map(r=>r.date.slice(0,7)))].filter(m=>m<current&&m>=data.startDate.slice(0,7)).sort().reverse();const select=document.getElementById('history-month'),previous=select.value;select.replaceChildren();months.forEach(m=>{const o=el('option',monthName(m));o.value=m;select.append(o)});select.disabled=!months.length;if(months.includes(previous))select.value=previous;if(months.length)renderView('history-view',select.value,data);else document.getElementById('history-view').textContent='Nessun mese precedente ancora disponibile.';select.onchange=()=>renderView('history-view',select.value,data);}
refresh();let shownMonth=monthKey();function checkMonth(){if(monthKey()!==shownMonth){shownMonth=monthKey();refresh()}}document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkMonth()});setInterval(checkMonth,60000);
}).catch(()=>{document.getElementById('current-expense-total').textContent='Non disponibile';['expense-view','history-view'].forEach(id=>document.getElementById(id).textContent='Impossibile caricare le spese. Ricarica la pagina.');});
})();
