const list=document.getElementById('list'),kind=document.getElementById('kind'),search=document.getElementById('search'),notice=document.getElementById('notice'),dialog=document.getElementById('editor'),form=document.getElementById('edit'),error=document.getElementById('error'),submit=document.getElementById('submit');let rows=[],selected=null,busy=false;
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format((n||0)/100);
const label=item=>item.type==='closing'?'Chiusura '+item.record.date:(item.record.supplier||item.record.name)+' · '+(item.record.invoiceNumber||item.record.documentNumber||'Spesa');
async function load(){const r=await fetch('/api/manage');if(!r.ok)throw Error(r.status===401?'Sessione scaduta. Torna alla panoramica ed effettua l’accesso.':'Caricamento non riuscito');rows=await r.json();draw();}
function draw(){list.replaceChildren();const shown=rows.filter(x=>x.type===kind.value&&JSON.stringify([x.record.date,label(x)]).toLocaleLowerCase().includes(search.value.toLocaleLowerCase())).sort((a,b)=>b.record.date.localeCompare(a.record.date));for(const item of shown){const row=document.createElement('article');row.className='row';const text=document.createElement('div');const h=document.createElement('strong');h.textContent=label(item);const p=document.createElement('p');p.textContent=item.record.date+' · '+money(item.type==='closing'?item.record.reportedTotal:item.record.amountCents);text.append(h,p);const actions=document.createElement('div');actions.className='tools';const edit=document.createElement('button');edit.textContent='Modifica';edit.onclick=()=>open(item);const del=document.createElement('button');del.textContent='Elimina';del.className='danger';del.onclick=()=>remove(item);actions.append(edit,del);row.append(text,actions);list.append(row);}if(!shown.length)list.textContent='Nessun documento trovato.';}
function open(item){selected=item;const r=item.record;form.reset();form.elements.date.value=r.date;form.elements.supplier.value=r.supplier||r.name||'';form.elements.number.value=r.invoiceNumber||r.documentNumber||'';form.elements.group.value=r.group||'Bar';const closing=item.type==='closing';for(const id of ['invoice-fields','closing-fields']){const active=id===(closing?'closing-fields':'invoice-fields');document.getElementById(id).hidden=!active;for(const e of document.querySelectorAll('#'+id+' input,#'+id+' select')){e.disabled=!active;e.required=active&&e.name!=='number';}}
for(const e of form.querySelectorAll('input[type=number]'))e.value=((r[e.name]||0)/100).toFixed(2);error.textContent='';dialog.showModal();}
async function mutate(body){const r=await fetch('/api/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Operazione non riuscita');}
async function remove(item){if(busy||!confirm('Eliminare '+label(item)+' di '+money(item.type==='closing'?item.record.reportedTotal:item.record.amountCents)+'? Verrà escluso dai totali.'))return;busy=true;try{await mutate({id:item.id,revision:item.revision,action:'delete'});await load();notice.textContent='Documento eliminato. Totali aggiornati.';}catch(e){notice.textContent=e.message}finally{busy=false;}}
form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;submit.disabled=true;try{const data=Object.fromEntries(new FormData(form));for(const e of form.querySelectorAll('input[type=number]:not(:disabled)'))data[e.name]=Math.round(Number(e.value)*100);await mutate({...data,id:selected.id,revision:selected.revision,action:'edit'});dialog.close();await load();notice.textContent='Modifiche salvate. Totali aggiornati.';}catch(e){error.textContent=e.message}finally{busy=false;submit.disabled=false;}};
document.getElementById('cancel').onclick=()=>{if(!busy)dialog.close()};kind.onchange=draw;search.oninput=draw;const preset=new URLSearchParams(location.search).get('type');if(['closing','invoice'].includes(preset))kind.value=preset;load().catch(e=>notice.textContent=e.message);
