(function(){
const currency=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}),money=n=>currency.format(n/100);
function currentMonth(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit'}).formatToParts(new Date());return p.find(x=>x.type==='year').value+'-'+p.find(x=>x.type==='month').value;}
const monthName=m=>new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T12:00:00Z'));
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
fetch('closings.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{
const select=document.getElementById('receipts-month');const months=[...new Set([currentMonth(),...data.map(r=>r.date.slice(0,7))])].sort().reverse();months.forEach(m=>{const o=el('option',monthName(m));o.value=m;select.append(o)});select.value=currentMonth();
function draw(){const month=select.value,rows=data.filter(r=>r.date.startsWith(month)),sum=key=>rows.reduce((n,r)=>n+r[key],0);const root=document.getElementById('receipts-summary');root.replaceChildren();const list=document.getElementById('receipts-list');list.replaceChildren();if(!rows.length){root.append(el('p','Nessuna chiusura acquisita per questo mese.'));return;}
const cards=el('div',undefined,'cards');[['Totale riportato sui fogli',sum('reportedTotal')],['POS annotato',sum('pos')],['Contanti annotati',sum('cashAfterOutflow')]].forEach(([label,n])=>{const c=el('article',undefined,'card');c.append(el('div',label,'eyebrow'),el('strong',money(n)));cards.append(c)});root.append(cards);const note=el('div',undefined,'notice');note.append(el('strong',rows.length+' chiusure acquisite'),el('p','Ogni chiusura è attribuita al giorno di inizio turno, dalle 17:00 alle 02:00 del giorno successivo. Asporto non sommato nuovamente. Per i pagamenti elettronici è utilizzato soltanto il POS.'));root.append(note);
rows.forEach(r=>{const panel=el('details',undefined,'panel');panel.style.marginBottom='16px';const head=el('summary',r.dateLabel+' · '+money(r.reportedTotal));head.style.cursor='pointer';panel.append(head);const box=el('div',undefined,'tablebox');box.style.marginTop='16px';const table=el('table'),body=el('tbody');[['Bar',r.barTotal],['Cucina',r.kitchenTotal],['Somma reparti',r.registeredTotal],['Asporto (non aggiunto)',r.takeawayHandwritten],['POS',r.pos],['Contanti',r.cashAfterOutflow],['Totale scritto sul foglio',r.reportedTotal]].forEach(([label,v])=>{const tr=el('tr');tr.append(el('td',label),el('td',money(v),'price'));body.append(tr)});table.append(body);box.append(table);panel.append(box);const a=el('a','Apri foto originale ↗','link');a.href=r.sources[0];a.target='_blank';a.rel='noopener';panel.append(a);list.append(panel)});
}
function overview(){const current=currentMonth(),rows=data.filter(r=>r.date.startsWith(current));document.getElementById('receipts-month-label').textContent='Chiusure · '+monthName(current);document.getElementById('receipts-month-total').textContent=rows.length?money(rows.reduce((n,r)=>n+r.reportedTotal,0)):'Da acquisire';document.getElementById('receipts-month-note').textContent=rows.length?rows.length+' fogli · totali riportati nelle chiusure.':'Nessuna chiusura ancora acquisita.';}
select.onchange=draw;overview();draw();let shown=currentMonth();setInterval(()=>{if(shown!==currentMonth()){shown=currentMonth();overview();const o=el('option',monthName(shown));o.value=shown;select.prepend(o);select.value=shown;draw()}},60000);
}).catch(()=>{document.getElementById('receipts-month-total').textContent='Non disponibile';document.getElementById('receipts-summary').textContent='Impossibile caricare le chiusure. Ricarica la pagina.'});
})();
